require "http"
require "log"
require "json"
require "colorize"
require "random/secure"
require "ecr"

require "./amber/version"
require "./amber/support/inflector"
require "./amber/adapters"
require "./amber/controller/**"
require "./amber/dsl/**"
require "./amber/exceptions/**"
require "./amber/extensions/**"
require "./amber/router/constraint"
require "./amber/router/constraint_presets"
require "./amber/router/constraints/*"
require "./amber/router/context"
require "./amber/pipes/**"
require "./amber/server/**"
require "./amber/validators/**"
require "./amber/websockets/**"
require "./amber/configuration"
require "./amber/router/named_routes"
require "./amber/router/route_printer"
require "./amber/environment"
require "./amber/schema/**"
require "./amber/markdown"
require "./amber/jobs"
require "./amber/mailer"

module Amber
  include Amber::Environment
end
